name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo
  repository_dispatch:
    types: [ push_event ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Delete Demo Contents
        run: rm -rf ./content/*

      - name: Clone Vault
        uses: actions/checkout@v2
        with:
          repository: aren227/obsidian-general-vault
          path: ./content
          token: ${{ secrets.VAULT_TOKEN }}

      - run: shopt -s extglob
      - run: cd ./content && rm -rf !(Wiki|_index.md)

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: aren227.me
